- alias: "New device detected"
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.global
    data:
      message: 'New device detected on network'
      title: 'New device'

