- alias: 'Everyone Gone'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.notify_home
        state: 'on'
  action:
    service: notify.global
    data:
      message: 'Everyone has now left'
      title: 'Home empty'
      data:
        url: https://ladyroad.duckdns.org:8123

- alias: 'Someone Home'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.notify_home
        state: 'on'
  action:
    service: notify.global
    data:
      message: 'Someone is now home'
      title: 'Home occupied'
      data:
        url: https://ladyroad.duckdns.org:8123

- alias: 'Update notifications'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.global
    data:
      message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
      data:
        url: "https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/#upgrading"

- alias: 'Notify download finished'
  trigger:
    - platform: event
      event_type: download_finished
      to: 'on'
  action:
    service: notify.global
    data_template:
      message: {{ trigger.event.data.data["message"] }}
      title: 'Download complete'
      data:
        url: https://ladyroad.duckdns.org:8123